# Generated by Django 5.0.3 on 2024-05-21 18:59

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerspark', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_status',
            field=models.CharField(choices=[('process', 'Processing'), ('vendor Cancel', 'Vendor Cancel'), ('delivered', 'Delivered'), ('client cancel', 'Client Cancel')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='qty',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='id_wishlist',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcde12345', length=10, max_length=20, prefix='wish', unique=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='qty',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
