# Generated by Django 5.0.3 on 2024-05-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerspark', '0003_alter_orderitem_product_status_alter_orderitem_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_status',
            field=models.CharField(choices=[('process', 'Processing'), ('vendor cancel', 'Vendor Cancel'), ('delivered', 'Delivered'), ('client cancel', 'Client Cancel')], default='processing', max_length=30),
        ),
    ]
